#ifndef _GA_QAP_H_
#define _GA_QAP_H_

#include <vector>
#include <algorithm>
#include <iostream>
#include "qap.h"

class GA_QAP 
{
	private:
		
		/* this is a QAP solution  */
		int* chromossome;

		int size_initial_population;

		std::vector<int*> population;

		/** instance size of QAP */
		int size_problem;

		QAP *problem;

	public:

		/**
		 * @brief      Constructs the object.
		 *
		 * @param      problem       The problem
		 * @param[in]  size_problem  The size problem
		 */
		GA_QAP(QAP *problem, int size_initial_population);

		/**
		 * @brief      Destroys the object.
		 */
		~GA_QAP();

		/**
		 * @brief      Generates an initial population randomly
		 */
		void generate_initial_population();

		/**
		 * @brief      Randomly select two individuals to apply crossover
		 *
		 * @return     the new individual generated
		 */
		int* selection ();

		/**
		 * @brief      Producing a new feasible solution (i.e., a child) 
		 			   by combining two individuals. 
		 *
		 * @param      i     the father
		 * @param      j     the mother
		 *
		 * @return     the new individual generated by combining i and j
		 */
		int* crossover(int* i, int* j);

		/**
		 * @brief       Increasing diversity in the population by introducing
		 				random variations in the members of the population. 
		 */
		void mutation();

		/**
		 * @brief      print the individuals of population
		 */
		void print_population();

		void run();

};


#endif